# -*- coding: utf-8 -*-
"""Model_Building.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuEZwga9Qh9N1LjjK_KRJkJgwgpNmJau
"""

import os

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!pip install mlflow
!pip install boto3 awscli
!pip install mlflow optuna xgboost
!pip install optuna optuna-integration[mlflow]
import optuna.integration.mlflow
import mlflow.sklearn
import pandas as pd
import numpy as np
import xgboost as xgb
import optuna.integration.mlflow
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import mlflow
import ast
import joblib
import matplotlib.pyplot as plt
import seaborn as sns

!aws configure
# Chemin vers les fichiers
os.makedirs("/content/drive/MyDrive/ProjetEts/models", exist_ok=True)
data_dir = "/content/drive/MyDrive/ProjetEts/HDFS_results/"
train_file = os.path.join(data_dir, "Event_occurence_matrix_HDFS_train.csv")
valid_file = os.path.join(data_dir, "Event_occurence_matrix_HDFS_valid.csv")

# Chargement des données
df_train = pd.read_csv(train_file)
df_valid = pd.read_csv(valid_file)

# Suppression des colonnes non pertinentes
X_train = df_train.drop(columns=["BlockId", "Label", "Time", "Date", "Type"], errors='ignore')
y_train = df_train["Label"].apply(lambda x: 1 if x == "Fail" else 0)

X_valid = df_valid.drop(columns=["BlockId", "Label", "Time", "Date", "Type"], errors='ignore')
y_valid = df_valid["Label"].apply(lambda x: 1 if x == "Fail" else 0)

# Définir l'expérience MLflow
mlflow.set_tracking_uri("http://ec2-18-207-206-140.compute-1.amazonaws.com:5000")
mlflow.set_experiment("HDFS")

with mlflow.start_run(run_name="RandomForest-HDFS") as run:
    # Modèle
    rf = RandomForestClassifier(n_estimators=100, random_state=42)
    rf.fit(X_train, y_train)

    # Log des paramètres
    mlflow.log_param("n_estimators", 100)
    mlflow.log_param("random_state", 42)

    # Log du modèle
    mlflow.sklearn.log_model(rf, "model")

    # Évaluation sur validation (calculs dans script suivant)
    val_score = rf.score(X_valid, y_valid)
    mlflow.log_metric("val_accuracy", val_score)

    print(f"✅ Modèle entraîné avec une précision sur validation : {val_score:.4f}")
    print(f"🔗 Run ID : {run.info.run_id}")

    #  Visualisation de l'importance des features ===
    importances = rf.feature_importances_
    feature_names = X_train.columns
    feature_df = pd.DataFrame({"Feature": feature_names, "Importance": importances})
    feature_df = feature_df.sort_values(by="Importance", ascending=False).head(20)

    plt.figure(figsize=(10, 6))
    sns.barplot(x="Importance", y="Feature", data=feature_df)
    plt.title("Top 20 Features Importantes - Random Forest")
    plt.tight_layout()

    # Sauvegarder localement
    fig_path = "/content/drive/MyDrive/ProjetEts/models/feature_importance.png"
    plt.savefig(fig_path)
    plt.close()

    # Enregistrer dans MLflow comme artefact
    mlflow.log_artifact(fig_path)






with mlflow.start_run(run_name="XGBoost-HDFS") as run:
    model = xgb.XGBClassifier(n_estimators=100, max_depth=5, use_label_encoder=False, eval_metric='logloss')
    model.fit(X_train, y_train)

    # Log des paramètres
    mlflow.log_param("model", "XGBoost")
    mlflow.log_param("n_estimators", 100)
    mlflow.log_param("max_depth", 5)

    # Log du modèle
    mlflow.sklearn.log_model(model, "model")

    # Évaluation
    val_score = model.score(X_valid, y_valid)
    mlflow.log_metric("val_accuracy", val_score)

    print(f"✅ XGBoost Accuracy : {val_score:.4f}")
    print(f"🔗 Run ID : {run.info.run_id}")

joblib.dump(rf, "/content/drive/MyDrive/ProjetEts/models/random_forest.pkl")

import os

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!pip install mlflow
!pip install boto3 awscli
!pip install mlflow optuna xgboost
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import mlflow
import mlflow.sklearn
import os
import ast
import joblib
!aws configure
# Chemin vers les fichiers
os.makedirs("/content/drive/MyDrive/ProjetEts/models", exist_ok=True)
data_dir = "/content/drive/MyDrive/ProjetEts/HDFS_results/"
train_file = os.path.join(data_dir, "Event_occurence_matrix_HDFS_train.csv")
valid_file = os.path.join(data_dir, "Event_occurence_matrix_HDFS_valid.csv")

# Chargement des données
df_train = pd.read_csv(train_file)
df_valid = pd.read_csv(valid_file)

# Suppression des colonnes non pertinentes
X_train = df_train.drop(columns=["BlockId", "Label", "Time", "Date", "Type"], errors='ignore')
y_train = df_train["Label"].apply(lambda x: 1 if x == "Fail" else 0)

X_valid = df_valid.drop(columns=["BlockId", "Label", "Time", "Date", "Type"], errors='ignore')
y_valid = df_valid["Label"].apply(lambda x: 1 if x == "Fail" else 0)

# Définir l'expérience MLflow
mlflow.set_tracking_uri("http://ec2-18-207-206-140.compute-1.amazonaws.com:5000")
mlflow.set_experiment("HDFS")

with mlflow.start_run(run_name="RandomForest-HDFS") as run:
    # Modèle
    rf = RandomForestClassifier(n_estimators=100, random_state=42)
    rf.fit(X_train, y_train)

    # Log des paramètres
    mlflow.log_param("n_estimators", 100)
    mlflow.log_param("random_state", 42)

    # Log du modèle
    mlflow.sklearn.log_model(rf, "model")

    # Évaluation sur validation (calculs dans script suivant)
    val_score = rf.score(X_valid, y_valid)
    mlflow.log_metric("val_accuracy", val_score)

    print(f"✅ Modèle entraîné avec une précision sur validation : {val_score:.4f}")
    print(f"🔗 Run ID : {run.info.run_id}")

joblib.dump(rf, "/content/drive/MyDrive/ProjetEts/models/random_forest.pkl")